Feature/file provider/create custom file provider
Ragnacodes/Mashgh pull request #7
Opened 2023-07-21 15:43 UTC by sharyash81

This PR contains the initial codes related to the way we handle file requests using MinIO

2023-07-22 05:56 UTC, Amin-MAG requested changes
Thanks, Arya for your changes, I tested the service and it worked fine. The structure and implementation of `s3` and `file_provider` are precisely what they should be!

2023-07-22 05:56 UTC, Amin-MAG commented on pkg/s3/minio.go
> +	if err != nil {
Use the `ctx` here. Let's not create a new `context.Background()`.

2023-07-22 05:56 UTC, Amin-MAG commented on pkg/s3/minio.go
> +	secretKey := cfg.MinIO.SecretKey
Remove the `l` (`logger.Logger`) argument if it is unnecessary.

2023-07-22 05:56 UTC, Amin-MAG commented on internal/mashgh/file_provider/s3.go
> +	return s.objectStorage.UploadFile(ctx, bucketName, objectName, data)
This is a bug. The bucket name should be `s.cfg.MinIO.ArticleBucket`.

2023-07-22 05:56 UTC, Amin-MAG commented on internal/mashgh/file_provider/s3.go
> +	return s.objectStorage.GetFileUrl(ctx, bucketName, objectName)
The same issue about bucket name is also here.

2023-07-22 05:56 UTC, Amin-MAG commented on internal/mashgh/file_provider/s3.go
> +
Please move this function to the end of the file. Let's follow this order.
- package names
- imports
- constants
- types
-  In my opinion, we should not have multiple `New()` functions in these packages. If so, they can be separated into multiple files. In case we have one New function, the first function after defining types should be `New()` function, and then the Methods of that returned type of `New()`.
-  non-exported functions

2023-07-22 13:05 UTC, Amin-MAG commented
Please change the name of the `file_provider` package and directory to `fprovider`.

2023-07-22 13:06 UTC, Amin-MAG commented on docker-compose-dev.yml
> +  minio_storage:
Please remove these two commented lines.

2023-07-22 13:11 UTC, Amin-MAG commented
At the moment, I think we can ignore the file types in the MinIO storage. It should not cause any issues. What's your opinion?

2023-07-22 13:13 UTC, Amin-MAG commented
Also, we should consider creating a new `.env.sample` file which contains all of the parameters without any given values. Because it is time-consuming to find the correct environment variables.

The file is something like this

```plain
# Database
POSTGRES_DB=mashgh_db
POSTGRES_PASSWORD=admin
POSTGRES_USER=admin
POSTGRES_PORT=5432

# Minio
Host=localhost
Port=9000
AccessKey=access
SecretKey=secret
UseSSL=false

# SMS Provider
SMS_PROVIDER_API_KEY=
```

2023-07-26 21:58 UTC, sharyash81 commented
> 



> At the moment, I think we can ignore the file types in the MinIO storage. It should not cause any issues. What's your opinion?

I agree with you since without mentioning the file type , it works fine and doing this , right now , isn't something important that we have to spend an extra effort on .

2023-07-26 22:01 UTC, sharyash81 commented
> Also, we should consider creating a new `.env.sample` file which contains all of the parameters without any given values. Because it is time-consuming to find the correct environment variables.
> 
> The file is something like this
> 
> ```
> # Database
> POSTGRES_DB=mashgh_db
> POSTGRES_PASSWORD=admin
> POSTGRES_USER=admin
> POSTGRES_PORT=5432
> 
> # Minio
> Host=localhost
> Port=9000
> AccessKey=access
> SecretKey=secret
> UseSSL=false
> 
> # SMS Provider
> SMS_PROVIDER_API_KEY=
> ```

Can you explain why we need this file ? just to avoid any mismatch that may be occurred because of ENV name ?

2023-07-27 16:51 UTC, Amin-MAG commented
> > Also, we should consider creating a new `.env.sample` file which contains all of the parameters without any given values. Because it is time-consuming to find the correct environment variables.
> > The file is something like this
> > ```
> > # Database
> > POSTGRES_DB=mashgh_db
> > POSTGRES_PASSWORD=admin
> > POSTGRES_USER=admin
> > POSTGRES_PORT=5432
> > 
> > # Minio
> > Host=localhost
> > Port=9000
> > AccessKey=access
> > SecretKey=secret
> > UseSSL=false
> > 
> > # SMS Provider
> > SMS_PROVIDER_API_KEY=
> > ```
> 
> Can you explain why we need this file ? just to avoid any mismatch that may be occurred because of ENV name ?


> > Also, we should consider creating a new `.env.sample` file which contains all of the parameters without any given values. Because it is time-consuming to find the correct environment variables.
> > The file is something like this
> > ```
> > # Database
> > POSTGRES_DB=mashgh_db
> > POSTGRES_PASSWORD=admin
> > POSTGRES_USER=admin
> > POSTGRES_PORT=5432
> > 
> > # Minio
> > Host=localhost
> > Port=9000
> > AccessKey=access
> > SecretKey=secret
> > UseSSL=false
> > 
> > # SMS Provider
> > SMS_PROVIDER_API_KEY=
> > ```
> 
> Can you explain why we need this file ? just to avoid any mismatch that may be occurred because of ENV name ?

We have ignored the file .env.local, It is correct because we do not want to have some local secrets on a git repository. First of all because of the security. Second, for the conflict between the developer's local settings. The issue is that sometimes there is a need to add a new key value to this file (In this case, Minio variables), It is not easy for other developers to find the correct "Key" values of these variables If we have a `.env.sample` file, developer will check this files to find out the available variables that he can set.

2023-07-27 16:54 UTC, Amin-MAG approved these changes

2023-07-27 17:01 UTC, merged